# Generated by Django 2.2.19 on 2023-02-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230201_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
